theme: jekyll-theme-slate

title: Rabi-Ribi Randomizer
description: Randomizes items in Rabi-Ribi maps
image: https://user-images.githubusercontent.com/27341392/29525297-bc4087d8-86c4-11e7-8c1a-235de711994d.gif
